# Generated by Django 5.0 on 2024-05-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('elapsed', models.FloatField()),
                ('algorithm', models.CharField(max_length=20)),
                ('num_primes', models.IntegerField()),
            ],
        ),
    ]
